version: '2'
services:
  hrono-rethinkdb-node-master:
    image: rethinkdb:2.3.5
    command: "rethinkdb --bind all"

  hrono-rethinkdb-node-slave:
    image: rethinkdb:2.3.5
    command: "rethinkdb --join hrono-rethinkdb-node-master --bind all"
    links:
      - hrono-rethinkdb-node-master

  hrono-rethinkdb-node-proxy:
    image: rethinkdb:2.3.5
    command: "rethinkdb proxy --join hrono-rethinkdb-node-master --bind all"
    ports:
      - "8080:8080"
      - "28015:28015"
    links:
      - hrono-rethinkdb-node-master